name: Pack and publish nuget packages
on:
  push:
    branches: [ "master" ]

jobs:
  pack-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pack template
        run: dotnet pack -c Release

      - name: Publish template to nuget
        run: dotnet nuget push bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }} --skip-duplicate
